
services:
  nginx:
    container_name: nginx
    build:
      context: nginx
      args:
        UID: ${UID}
        GID: ${GID}
    ports:
      - "8090:80"
    volumes:
      - website:/var/www/html

  php:
    container_name: php
    build:
      context: php
      args:
        UID: ${UID}
        GID: ${GID}
    volumes:
      - website:/var/www/html

volumes:
  website:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DATA_DIR}/website
