services:
  nginx:
    build:
      context: nginx 
      dockerfile: Dockerfile
    ports:
      - "8090:80"
    volumes:
      - website:/var/www/html

  php:
    image: php:7.4-fpm
    volumes:
      - website:/var/www/html

volumes:
  website:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ${DATA_DIR}/website
